spring.application.name=AuthFlow

spring.datasource.url=jdbc:mysql://localhost:3306/authFlowDb
spring.datasource.username=root
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

jwt.secret.key=FjqelDleeljX2X4Bqw2k7WFM76dDzOPKpilnDSDNrrT